
_BASE_:
  - '../ppyoloe/ppyoloe_plus_crn_m_80e_coco.yml'

find_unused_parameters: False

log_iter: 20
snapshot_epoch: 10
save_interval: 10

metric: COCO
num_classes: 1

# ==========================
# Training
# ==========================
epoch: 150
worker_num: 12
use_gpu: true

save_dir: /home/aistudio/outputM2

weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_plus_crn_m_obj365_pretrained.pdparams

use_ema: true

PPYOLOEHead:
  num_classes: 1
  static_assigner_epoch: 30

# ==========================
# Dataset
# ==========================
TrainDataset:
  !COCODataSet
  image_dir: train/images
  anno_path: annotations/train.json
  dataset_dir: /home/aistudio/competition/dataset
  data_fields:
    - image
    - gt_bbox
    - gt_class
  allow_empty: false

EvalDataset:
  !COCODataSet
  image_dir: val/images
  anno_path: annotations/val.json
  dataset_dir: /home/aistudio/competition/dataset

TestDataset:
  !ImageFolder
  anno_path: ""
  dataset_dir: /home/aistudio/competition/dataset

# ==========================
# Learning Rate
# ==========================
LearningRate:
  base_lr: 0.0005

  schedulers:
    - !CosineDecay
      max_epochs: 150

    - !LinearWarmup
      start_factor: 0.0
      epochs: 3

OptimizerBuilder:
  clip_grad_by_norm: 35.

# ==========================
# TrainReader
# ==========================
TrainReader:
  batch_size: 12
  shuffle: true
  drop_last: true
  use_shared_memory: true

  sample_transforms:
    - Decode: {}

    - RandomFlip:
        prob: 0.5
    - RandomDistort: {}
    # - RandomDistort:
    #     brightness_lower: 0.9
    #     brightness_upper: 1.1
    #     contrast_lower: 0.9
    #     contrast_upper: 1.1
    #     saturation_lower: 0.9
    #     saturation_upper: 1.1
    #     hue_prob: 0.2

    - Resize:
        target_size: [640, 640]
        keep_ratio: false
        interp: 2

    - NormalizeImage:
        is_scale: true
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

    - Permute: {}

  batch_transforms:
    - PadGT:
        return_gt_mask: true

# ==========================
# EvalReader
# ==========================
EvalReader:
  batch_size: 8

  sample_transforms:
    - Decode: {}

    - Resize:
        target_size: [640, 640]
        keep_ratio: false
        interp: 2

    - NormalizeImage:
        is_scale: true
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

    - Permute: {}

# ==========================
# TestReader
# ==========================
TestReader:
  batch_size: 8

  sample_transforms:
    - Decode: {}

    - Resize:
        target_size: [640, 640]
        keep_ratio: false
        interp: 2

    - NormalizeImage:
        is_scale: true
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

    - Permute: {}
